version: '3'

networks:
  soketi:
    driver: bridge

services:
  libp2p-local:
    image: soketi/server:libp2p-local
    deploy:
      replicas: 3
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint:
        - node
        - --experimental-specifier-resolution=node
        - --trace-warnings
        - --experimental-vm-modules
        - packages/servers/dist/src/servers/libp2p-server.js
    ports:
      - 6001-6003:6001
      - 7001-7003:7001
    environment:
      - DEBUG=libp2p:*
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - soketi
