name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - "**.md"
      - "benchmark/**"
      - ".github/workflows/benchmark.yml"
      - ".github/workflows/docker-*.yml"
      - ".github/*.yml"
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        node:
          - 16.x
          - 18.x
          - 20.x

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3.4.1
        name: Setup Node.js v${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}

      # Cache node dependencies
      - uses: actions/cache@v3.0.7
        name: Cache Node.js dependencies
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Execute lint & build
        run: |
          npm run lint
          npm run build

      - name: Execute tests
        run: npm run test

      - uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
